// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace TVShowsAPI.Data.Models;

public partial class TVShowDataContext : DbContext
{
    private readonly IConfiguration _configuration;

    public TVShowDataContext ( )
    {
    }

    public TVShowDataContext ( DbContextOptions<TVShowDataContext> options , IConfiguration configuration )
        : base ( options )
    {
        _configuration = configuration;
    }

    public virtual DbSet<TvShow> TvShows { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring ( DbContextOptionsBuilder optionsBuilder )
    {
        if (optionsBuilder.IsConfigured)
        {
            // Obtén la cadena de conexión desde IConfiguration
            var connectionString = _configuration.GetConnectionString ( "DefaultConnection" );
            optionsBuilder.UseSqlServer ( connectionString );
        }
    }

    protected override void OnModelCreating ( ModelBuilder modelBuilder )
    {
        modelBuilder.Entity<TvShow> ( entity =>
        {
            entity.HasKey ( e => e.Id ).HasName ( "PK__TvShows__3214EC0763762B10" );
        } );

        modelBuilder.Entity<User> ( entity =>
        {
            entity.HasKey ( e => e.Id ).HasName ( "PK__Users__3214EC0748D88194" );
        } );

        OnModelCreatingPartial ( modelBuilder );
    }

    partial void OnModelCreatingPartial ( ModelBuilder modelBuilder );
}