// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TVShowsAPI.Data.Models;

public partial class TvShow
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    public bool Favorite { get; set; }

    [Required]
    [StringLength(255)]
    public string Content { get; set; }

    [Required]
    [StringLength(255)]
    public string Format { get; set; }

    [Required]
    [StringLength(255)]
    public string Episodes { get; set; }

    [Required]
    [StringLength(50)]
    public string Duration { get; set; }

    [Required]
    [StringLength(255)]
    public string Scenarios { get; set; }

    [Required]
    [StringLength(50)]
    public string Classification { get; set; }
}